### ISSUE TITLE
sample for CentOS and Ubuntu?

### ISSUE THREAD

**Issue by timiil** [ferrarimarco/pxe#8]
Hi, very great container. but please just give it a sample to CentOS and Ubuntu whould be very nice :)

**Comment by ferrarimarco** [comment]
Hi! You can see an exmple (Ubuntu) in the README of this project. Additionally you can have a look at this project (for now check the development branch): https://github.com/ferrarimarco/home-lab-dnsmasq/tree/development

It's an image based on this one with a working Ubuntu 16.04 (x86 and x64) PXE
